# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 54ebcb1642c1ce2c718f9b0b37f68f3726aa9469c27299b1b8cce3071ff2bfd49b962489255ca1f8a815f5c4f2ccdf47d50a5a6b54cf2112c17efaa612fa0a5d

test:
  secret_key_base: 60c22b4f602c159cb24caef2bde3f9f7ae4b855f4c00951e37dd2ce41d198874dc545e37793a70e71b974e291e20085e0f98dca2c1b113ffb55fec92b927b0a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
